# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_kid_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='kid',
            name='savings_match',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
