# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
