# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='cards.Card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='cards.Card')),
            ],
        ),
    ]
