# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('global', 'Global'), ('merchant', 'Merchant')], max_length=100)),
                ('merchant_type', models.CharField(blank=True, choices=[('MCT_ADULT_ENTERTAINMENT', 'Adult Entertainment'), ('MCT_AIRFARE', 'Airfare'), ('MCT_ALCOHOL', 'Alcohol'), ('MCT_APPAREL_AND_ACCESSORIES', 'Apparel and Accesories'), ('MCT_AUTOMOTIVE', 'Automotive'), ('MCT_CAR_RENTAL', 'Car Rental'), ('MCT_ELECTRONICS', 'Electronics'), ('MCT_ENTERTAINMENT_AND_SPORTINGEVENTS', 'Entertainment and Sporting Events'), ('MCT_GAMBLING', 'Gambling'), ('MCT_GAS_AND_PETROLEUM', 'Gas and Petroleum'), ('MCT_GROCERY', 'Grocery'), ('MCT_HOTEL_AND_LODGING', 'Hotel and Lodging'), ('MCT_HOUSEHOLD', 'Household'), ('MCT_PERSONAL_CARE', 'Personal Care'), ('MCT_RECREATION', 'Recreation'), ('MCT_SMOKE_AND_TOBACCOsmoke_and_tobacco', 'Smoke and Tobacco')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='visa_document_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rule',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
        ),
    ]
