# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 05:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20160417_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='merchant_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MCT_ADULT_ENTERTAINMENT', 'Adult Entertainment'), ('MCT_AIRFARE', 'Airfare'), ('MCT_ALCOHOL', 'Alcohol'), ('MCT_APPAREL_AND_ACCESSORIES', 'Apparel and Accesories'), ('MCT_AUTOMOTIVE', 'Automotive'), ('MCT_CAR_RENTAL', 'Car Rental'), ('MCT_ELECTRONICS', 'Electronics'), ('MCT_ENTERTAINMENT_AND_SPORTINGEVENTS', 'Entertainment and Sporting Events'), ('MCT_GAMBLING', 'Gambling'), ('MCT_GAS_AND_PETROLEUM', 'Gas and Petroleum'), ('MCT_GROCERY', 'Grocery'), ('MCT_HOTEL_AND_LODGING', 'Hotel and Lodging'), ('MCT_HOUSEHOLD', 'Household'), ('MCT_PERSONAL_CARE', 'Personal Care'), ('MCT_RECREATION', 'Recreation'), ('MCT_SMOKE_AND_TOBACCOsmoke_and_tobacco', 'Smoke and Tobacco')], max_length=255), blank=True, default=list, size=None),
        ),
    ]
