# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 11:17
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20160417_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='card',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
